"""empty message

Revision ID: 2fdffb145fe7
Revises: 340870ee6a41
Create Date: 2019-10-24 23:09:32.068213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdffb145fe7'
down_revision = '340870ee6a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('locality', 'restaurants', ['location_locality'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('locality', table_name='restaurants')
    # ### end Alembic commands ###
