"""empty message

Revision ID: 340870ee6a41
Revises: 
Create Date: 2019-10-24 01:42:38.921247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340870ee6a41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_name', sa.String(), nullable=True),
    sa.Column('res_photo_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('average_cost', sa.Integer(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=True),
    sa.Column('open_time', sa.String(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_locality', sa.String(), nullable=True),
    sa.Column('location_zone_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('zone_name', 'zones', ['zone_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('zone_name', table_name='zones')
    op.drop_table('zones')
    op.drop_table('restaurants')
    op.drop_table('restaurant_score')
    # ### end Alembic commands ###
