"""empty message

Revision ID: 5646b1841f56
Revises: 9b968690f6bb
Create Date: 2019-10-25 06:18:28.659669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5646b1841f56'
down_revision = '9b968690f6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_score', sa.Column('score', sa.ARRAY(sa.String(), dimensions=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_score', 'score')
    # ### end Alembic commands ###
