"""empty message

Revision ID: 96240b75e91d
Revises: 
Create Date: 2019-10-25 04:15:35.572582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96240b75e91d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('zone_name', 'zones', ['zone_name'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_name', sa.String(), nullable=True),
    sa.Column('res_photo_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('average_cost', sa.Integer(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=True),
    sa.Column('open_time', sa.String(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_locality', sa.String(), nullable=True),
    sa.Column('location_zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('locality', 'restaurants', ['location_locality'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('locality', table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index('zone_name', table_name='zones')
    op.drop_table('zones')
    op.drop_table('restaurant_score')
    # ### end Alembic commands ###
