"""empty message

Revision ID: 9b968690f6bb
Revises: 96240b75e91d
Create Date: 2019-10-25 06:10:40.195400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b968690f6bb'
down_revision = '96240b75e91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'restaurant_score', 'restaurants', ['res_id'], ['id'])
    op.drop_column('restaurant_score', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_score', sa.Column('score', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'restaurant_score', type_='foreignkey')
    # ### end Alembic commands ###
